"""
SYNTHETIC DEMO DATA GENERATOR — READ BEFORE USING

The repository contains NO real historical train-delay dataset. It only contains
the static schedule/route catalog extracted to `ml/data/catalog.json` (real train
numbers, real stations, real distances, real scheduled times).

This module generates a **synthetic demo dataset** so the whole ML pipeline can be
developed, exercised and tested end-to-end. The data is generated by simulating
plausible delay behaviour on top of the REAL route structure (the actual stop
order, distances and scheduled times from `src/data/trainData.ts`).

:warning: This data is SYNTHETIC and labelled as such everywhere. It must NOT be
presented as real historical IRCTC/NTIS data. To train on real data, drop a CSV
matching the documented schema into `ml/data/real/train_delays.csv` — the training
pipeline automatically prefers the real file when present.

Simulation model (documented, reproducible, seeded):
  delay(level)   = level_0 + seasonal_effect + weekday_effect + weather_noise
  delay grows at each stop by a per-train trend term, an incident term, and a
  partial-recovery term when the train is already running late. Speed degrades
  when the train is heavily delayed (cascading congestion).
"""

from __future__ import annotations

import csv
import hashlib
from datetime import date, timedelta
from pathlib import Path

import numpy as np

from ml import config as cfg

# Season mapping used across the pipeline (must match ml.features).
SEASONS = {(12, 1, 2): "winter", (3, 4, 5): "summer", (6, 7, 8, 9): "monsoon", (10, 11): "post_monsoon"}


def season_of(d: date) -> str:
    for months, name in SEASONS.items():
        if d.month in months:
            return name
    return "winter"


TIME_PREFIXES = ["Source", "Expected", "Destination"]


def minutes_from_str(t: str) -> float | None:
    """Parse 'HH:MM AM/PM' or 'HH:MM' into minutes-of-day; None for non-times."""
    if not t:
        return None
    t = str(t).strip()
    for pre in TIME_PREFIXES:
        if t.startswith(pre):
            t = t.replace(pre, "", 1).strip()
    if not t or t.lower() in ("", "source", "destination", "na"):
        return None
    t = t.upper().replace(" ", "")
    try:
        if t.endswith("AM") or t.endswith("PM"):
            raw = t[:-2]
            hr, mi = map(int, raw.split(":"))
            ampm = t[-2:]
            if ampm == "PM" and hr != 12:
                hr += 12
            if ampm == "AM" and hr == 12:
                hr = 0
        else:
            hr, mi = map(int, t.split(":"))
        return float(hr * 60 + mi)
    except (ValueError, AttributeError):
        return None


def _seed_for(train_number: str, d: date) -> int:
    """Deterministic RNG seed per train+date so regeneration is reproducible."""
    h = hashlib.sha256(f"{train_number}:{d.isoformat()}".encode()).digest()
    return int.from_bytes(h[:8], "big") % (2**31)


def _as_float(x) -> float:
    try:
        return float(x)
    except (TypeError, ValueError):
        return 0.0


def _repr_seconds(s) -> str:
    return f"00:{int(s // 60):02d}:{int(s % 60):02d}"


def synthesize(seed: int = cfg.RANDOM_STATE) -> Path:
    """
    Generate the synthetic demo dataset and return the output CSV path.

    One row per (train, journey date, station) with `delay_next_minutes` being
    the target used for supervised training.
    """
    cfg.ensure_dirs()
    catalog = __import__("json").loads(Path(cfg.CATALOG_FILE).read_text(encoding="utf-8"))

    START = date(2024, 1, 1)
    END = date(2026, 6, 30)  # ~2.5 years of daily journeys
    rng = np.random.default_rng(seed)

    # Per-train-type severity priors (arbitrary but documented demo priors).
    type_bias = {
        "Vande Bharat": 5.0,
        "Rajdhani": 12.0,
        "Shatabdi": 9.0,
        "Duronto": 16.0,
        "Superfast": 22.0,
        "Express": 26.0,
    }

    rows = []
    day_count = (END - START).days + 1
    journeys = 0
    stations_total = 0

    for train in catalog["trains"]:
        tnum = train["trainNumber"]
        ttype = train["type"]
        bias = type_bias.get(ttype, 15.0)
        route = train["route"]
        if len(route) < 2:
            continue

        stops = [(s["stationCode"], _as_float(s["distanceKm"])) for s in route]
        sched_times = [minutes_from_str(s["scheduledArrival"]) for s in route]
        sched_dep = [minutes_from_str(s["scheduledDeparture"]) for s in route]
        halts = [_as_float(s["haltMinutes"]) for s in route]

        base_dep = sched_dep[0] if sched_dep[0] is not None else 360.0

        for offset in range(day_count):
            d = START + timedelta(days=offset)
            rng2 = np.random.default_rng(_seed_for(tnum, d))

            # Season / weekday / incident components
            season = season_of(d)
            season_w = {"winter": 6.0, "summer": 10.0, "monsoon": 28.0, "post_monsoon": 8.0}[season]
            dow = d.weekday()  # 0=Mon..6=Sun
            dow_w = [4.0, 3.0, 3.0, 4.0, 9.0, 8.0, 7.0][dow]
            incident = max(0.0, rng2.normal(10.0, 18.0))  # >= 0

            level = clamp(bias + season_w + dow_w + incident * rng2.random(), 0, 240)

            # Per-journey delay state
            for i, (code, dist) in enumerate(stops):
                sched_arr = sched_times[i]
                sched_dep_i = sched_dep[i]

                trend = max(0.0, rng2.normal(1.2, 0.6))
                speed_kmh = 90.0 + rng2.normal(0, 15)
                if level > 60:
                    speed_kmh = max(40.0, speed_kmh - 25.0)  # cascade congestion

                # Delay at THIS station arrives already accumulated from upstream.
                delay_current = max(0.0, level)

                # Next-station delay = current + trend + incident - partial recovery
                recovery = max(0.0, delay_current * rng2.uniform(0.0, 0.25))
                delay_next = max(0.0, delay_current + trend + (rng2.normal(4, 10) if rng2.random() < 0.22 else 0.0) - recovery)
                level = delay_next

                sched_arr_min = sched_arr if sched_arr is not None else (base_dep + 30 * i)
                delay_at_next_arr = 0.0
                if i + 1 < len(stops):
                    nxt_arr = sched_times[i + 1]
                    if nxt_arr is not None:
                        delay_at_next_arr = delay_next
                    else:
                        delay_at_next_arr = delay_next
                else:
                    delay_at_next_arr = delay_current  # terminus

                # descriptions for the row
                travel_planned = (sched_arr_min - base_dep) if sched_arr_min is not None else 30 * i

                rows.append(
                    {
                        "journey_date": d.isoformat(),
                        "train_number": tnum,
                        "train_name": train["trainName"],
                        "train_type": ttype,
                        "season": season,
                        "day_of_week": dow,
                        "is_weekend": 1 if dow >= 5 else 0,
                        "month": d.month,
                        "source_code": train["sourceCode"],
                        "destination_code": train["destinationCode"],
                        "direction": train["direction"],
                        "station_code": code,
                        "station_index": i,
                        "total_stops": len(stops),
                        "stops_remaining": len(stops) - 1 - i,
                        "distance_km": dist,
                        "total_distance_km": _as_float(train["distanceKm"]),
                        "remaining_distance_km": max(0.0, _as_float(train["distanceKm"]) - dist),
                        "distance_to_next_km": (
                            stops[i + 1][1] - dist if i + 1 < len(stops) else 0.0
                        ),
                        "progress_ratio": dist / max(1e-6, _as_float(train["distanceKm"])),
                        "scheduled_departure_hour": (base_dep % 1440) / 60.0,
                        "scheduled_arrival_minutes": sched_arr_min,
                        "scheduled_elapsed_minutes": travel_planned,
                        "cumulative_halt_minutes": float(sum(halts[:i])),
                        "halt_minutes": halts[i],
                        "delay_current_minutes": round(delay_current, 1),
                        "current_speed_kmh": round(speed_kmh, 1),
                        "delay_next_minutes": round(delay_at_next_arr, 1),
                        # clear provenance label
                        "data_source": "SYNTHETIC_DEMO",
                        "sim_seed": seed,
                    }
                )
                stations_total += 1
            journeys += 1

    # Historical-average lag features are computed in ml.features (train-fold only).
    with open(cfg.SYNTHETIC_FILE, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    print(f"[synthetic] Wrote {len(rows)} rows ({journeys} journeys, {stations_total} station-rows)")
    print(f"[synthetic] Output: {cfg.SYNTHETIC_FILE}  <-- SYNTHETIC DEMO DATA")
    return cfg.SYNTHETIC_FILE


def clamp(x, lo, hi):
    return max(lo, min(hi, x))


if __name__ == "__main__":
    synthesize()